name: docker-compose-actions-workflow
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths-ignore:
      - 'DCOS/**'
      - 'K8s/**'
      - 'load-gen/**'
      - 'OpenShift/**'
      - 'Swarm/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install docker-compose
        run: sudo apt-get -y install docker-compose
      - name: Build the stack
        run: docker-compose build
